version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 3001
      POSTGRES_DB: postgres
    volumes:
      - ./:/init_db.py
    ports:
      - 3001:3001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #command: cmd args
  backend:
    image: backend
    hostname: backend
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 3001
      POSTGRES_DB: postgres
    ports:
      - 5000:5000
  frontend:
    image: frontend
    hostname: frontend
    restart: always
    ports:
      - 3000:3000
